# Generated by Django 5.2.4 on 2026-01-17 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("contact_phone", models.CharField(blank=True, max_length=15)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("CSE", "CSE"),
                            ("ISE", "ISE"),
                            ("AIML", "AI & ML"),
                            ("IOT", "IoT"),
                            ("CYBER", "Cyber Security"),
                            ("DS", "Data Science"),
                            ("EC", "ECE"),
                            ("CIVIL", "Civil Engineering"),
                            ("MECH", "Mechanical Engineering"),
                            ("CSA", "CSA"),
                            ("MCA", "MCA"),
                            ("BCA", "BCA"),
                            ("MBA", "MBA"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TodoTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("for_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
                ),
                ("is_done", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=35)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("expertise", models.CharField(blank=True, max_length=200)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "cv",
                    models.FileField(blank=True, null=True, upload_to="trainer_cvs/"),
                ),
                ("is_full_time", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_met",
                    models.CharField(
                        help_text="HOD / Faculty / Coordinator name", max_length=100
                    ),
                ),
                (
                    "follow_up_type",
                    models.CharField(
                        choices=[
                            ("proposal", "Send Proposal"),
                            ("call", "Follow-up Call"),
                            ("meeting", "Meeting"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("follow_from", models.DateField()),
                ("follow_to", models.DateField()),
                ("reminder_date", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workshop_manager.college",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True, to="workshop_manager.department"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_full_time": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workshop_manager.trainer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowUpReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remind_at", models.DateTimeField()),
                ("message", models.CharField(blank=True, max_length=255)),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "followup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="workshop_manager.followup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_on", models.DateTimeField()),
                ("sent", models.BooleanField(default=False)),
                (
                    "follow_up",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workshop_manager.followup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "parent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="workshop_manager.todotask",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="todotask",
            name="trainer",
            field=models.ForeignKey(
                limit_choices_to={"is_full_time": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="workshop_manager.trainer",
            ),
        ),
        migrations.CreateModel(
            name="OfficeTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("batch_id", models.CharField(max_length=50)),
                (
                    "batch",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=10,
                    ),
                ),
                (
                    "hall",
                    models.CharField(
                        blank=True,
                        choices=[("hall1", "Hall 1"), ("hall2", "Hall 2")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("trainers", models.ManyToManyField(to="workshop_manager.trainer")),
            ],
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("tentative", "Tentative"),
                            ("fixed", "Fixed"),
                            ("postponed", "Postponed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="tentative",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "report",
                    models.FileField(
                        blank=True, null=True, upload_to="workshop_reports/"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "assigned_trainers",
                    models.ManyToManyField(blank=True, to="workshop_manager.trainer"),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workshop_manager.college",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True, to="workshop_manager.department"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="followup",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workshop_manager.workshop",
            ),
        ),
    ]
