# Generated by Django 5.2.4 on 2025-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainer",
            name="user",
        ),
        migrations.AddField(
            model_name="trainer",
            name="Name",
            field=models.CharField(default="me", max_length=35),
            preserve_default=False,
        ),
    ]
