# Generated by Django 5.2.4 on 2026-01-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workshop",
            name="departments",
        ),
        migrations.AddField(
            model_name="workshop",
            name="departments",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CSE", "CSE"),
                    ("ISE", "ISE"),
                    ("AIML", "AI & ML"),
                    ("IOT", "IoT"),
                    ("CYBER", "Cyber Security"),
                    ("DS", "Data Science"),
                    ("EC", "ECE"),
                    ("CIVIL", "Civil Engineering"),
                    ("MECH", "Mechanical Engineering"),
                    ("CSA", "CSA"),
                    ("MCA", "MCA"),
                    ("BCA", "BCA"),
                    ("MBA", "MBA"),
                ],
                max_length=50,
            ),
        ),
    ]
