# Generated by Django 5.2.4 on 2025-07-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0002_remove_trainer_user_trainer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("batch_id", models.CharField(max_length=50)),
                (
                    "batch",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=10,
                    ),
                ),
                (
                    "hall",
                    models.CharField(
                        blank=True,
                        choices=[("hall1", "Hall 1"), ("hall2", "Hall 2")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("trainers", models.ManyToManyField(to="workshop_manager.trainer")),
            ],
        ),
    ]
