# Generated by Django 5.2.4 on 2026-06-08 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0002_remove_workshop_departments_workshop_departments"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopRemarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topics_covered",
                    models.TextField(help_text="Topics covered during workshop"),
                ),
                (
                    "activities_conducted",
                    models.TextField(
                        blank=True,
                        help_text="Hands-on sessions, quizzes, projects etc.",
                    ),
                ),
                (
                    "blockers_faced",
                    models.TextField(
                        blank=True, help_text="Challenges faced during workshop"
                    ),
                ),
                (
                    "learning_outcomes",
                    models.TextField(
                        blank=True, help_text="What trainer learned from this workshop"
                    ),
                ),
                (
                    "innovation_added",
                    models.TextField(
                        blank=True,
                        help_text="Unique teaching methods, demos, activities",
                    ),
                ),
                ("notes_prepared", models.BooleanField(default=False)),
                ("notes_link", models.URLField(blank=True, null=True)),
                ("student_feedback", models.TextField(blank=True)),
                ("improvement_suggestions", models.TextField(blank=True)),
                ("overall_rating", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workshop_manager.trainer",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_reports",
                        to="workshop_manager.workshop",
                    ),
                ),
            ],
        ),
    ]
