# Generated by Django 5.2.4 on 2025-07-05 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0003_officetraining"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="is_full_time",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TodoTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=255)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("for_date", models.DateField(default=django.utils.timezone.now)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workshop_manager.trainer",
                    ),
                ),
            ],
        ),
    ]
