# Generated by Django 5.2.4 on 2025-10-09 13:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0004_trainer_is_full_time_todotask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todotask",
            name="date_created",
        ),
        migrations.AddField(
            model_name="todotask",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todotask",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todotask",
            name="estimated_hours",
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="todotask",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="todotask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "parent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="workshop_manager.todotask",
                    ),
                ),
            ],
        ),
    ]
