# Generated by Django 5.2.4 on 2025-10-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workshop_manager",
            "0005_remove_todotask_date_created_todotask_created_on_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
