# Generated by Django 5.2 on 2026-09-09 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0005_meetingnote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="todotask",
            name="for_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CSE", "CSE"),
                            ("ISE", "ISE"),
                            ("AIML", "AI & ML"),
                            ("IOT", "IoT"),
                            ("CYBER", "Cyber Security"),
                            ("DS", "Data Science"),
                            ("EC", "ECE"),
                            ("CIVIL", "Civil Engineering"),
                            ("MECH", "Mechanical Engineering"),
                            ("CSA", "CSA"),
                            ("MCA", "MCA"),
                            ("BCA", "BCA"),
                            ("MBA", "MBA"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("fdp", "FDP"),
                            ("online_workshop", "Online Workshop"),
                            ("office", "Office Training"),
                            ("guest_training", "Guest Faculty Training"),
                            ("meeting", "Meeting"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("guest_faculty", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="workshop_manager.college",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="calendar_events",
                        to="workshop_manager.trainer",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="workshop_manager.workshop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="workshop_manager.trainer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-check_in"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trainer", "date"),
                        name="unique_trainer_attendance_per_day",
                    )
                ],
            },
        ),
    ]
