# Generated by Django 5.2.4 on 2025-10-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0006_alter_subtask_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todotask",
            name="trainer",
            field=models.ForeignKey(
                limit_choices_to={"is_full_time": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="workshop_manager.trainer",
            ),
        ),
    ]
