# Generated by Django 5.2.4 on 2026-08-09 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0006_calendarevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarevent",
            options={},
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="trainer",
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CSE", "CSE"),
                    ("ISE", "ISE"),
                    ("AIML", "AI & ML"),
                    ("IOT", "IoT"),
                    ("CYBER", "Cyber Security"),
                    ("DS", "Data Science"),
                    ("EC", "ECE"),
                    ("CIVIL", "Civil Engineering"),
                    ("MECH", "Mechanical Engineering"),
                    ("CSA", "CSA"),
                    ("MCA", "MCA"),
                    ("BCA", "BCA"),
                    ("MBA", "MBA"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="trainers",
            field=models.ManyToManyField(
                blank=True,
                related_name="calendar_events",
                to="workshop_manager.trainer",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_events",
                to="workshop_manager.college",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("workshop", "Workshop"),
                    ("office", "Office Training"),
                    ("meeting", "Meeting"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
