# Generated by Django 5.2 on 2026-09-17 01:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0007_add_guest_faculty"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("learning", models.TextField(help_text="What did you learn today?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_learnings",
                        to="workshop_manager.trainer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trainer", "date"), name="unique_trainer_daily_learning"
                    )
                ],
            },
        ),
    ]
