# Generated by Django 5.2 on 2026-09-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0008_dailylearning"),
    ]

    operations = [
        migrations.AddField(
            model_name="todotask",
            name="category",
            field=models.CharField(
                choices=[
                    ("training", "Training"),
                    ("preparation", "Preparation"),
                    ("development", "Development"),
                    ("content", "Content Development"),
                    ("research", "Research"),
                    ("meeting", "Meeting"),
                    ("documentation", "Documentation"),
                    ("admin", "Administration"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="trainer_photos/"),
        ),
    ]
