# Generated by Django 5.2 on 2026-09-21 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop_manager", "0009_todotask_category_trainer_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todotask",
            name="calendar_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_work_tasks",
                to="workshop_manager.calendarevent",
            ),
        ),
        migrations.AddField(
            model_name="todotask",
            name="office_training",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_work_tasks",
                to="workshop_manager.officetraining",
            ),
        ),
        migrations.AddField(
            model_name="todotask",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_work_tasks",
                to="workshop_manager.workshop",
            ),
        ),
    ]
